[package]
name = "interthread"
version = "0.1.0"
edition = "2021"
description = "Auto implementation of the Actor Model"
license = "MIT OR Apache-2.0"
author = "Simon Nour"
repository = "https://github.com/NimonSour/interthread.git"
keywords = ["actor","actor-model","concurrency","parallelism"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]

quote = { version = "1" }
syn   = { version = "2", features = ["parsing","full","extra-traits"]}
proc-macro2 = { version = "1" }
proc-macro-error = { version = "1" }
proc-macro-crate = "1.3.1"