[package]
name = "interthread"
version = "0.3.0"
edition = "2021"
description = "Auto implementation of the Actor Model"
license = "MIT OR Apache-2.0"
author = "Simon Nour"
repository = "https://github.com/NimonSour/interthread.git"
keywords = ["actor","async","thread","interthread","actor-model"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]

quote = { version = "1" }
syn   = { version = "2", features = ["parsing","full","extra-traits"]}
proc-macro2      = { version = "1" }
proc-macro-error = { version = "1" }
proc-macro-crate = "1.3.1"
prettyplease     = "0.2.10"

[dev-dependencies]
smol          = "1.3.0"
oneshot       = { version = "0.1.5"}
async-channel = "1.8.0"
tokio         = { version="1.28.2" ,features=["full"] }
async-std     = { version = "1.12.0", features = ["attributes"] }